# -*- coding: utf-8 -*-
"""LTX23_Director_MV.ipynb

Automatically generated by Colab.

# **LTX-2.3 Director 2.0 Multi-View Workflow (30s)**

- This notebook runs the LTX-2.3 Director 2.0-MV workflow programmatically
  using ComfyUI NODE_CLASS_MAPPINGS without the GUI.
- Generates cinematic video with audio using the Director pipeline with
  spatial upscaling and two-stage sampling.

- Models source: https://huggingface.co/Kijai/LTXV2_comfy
- Director nodes: https://github.com/whatdreamscost/whatdreamscost-comfyui
"""

import subprocess
import os
import sys
from pathlib import Path
from typing import Sequence, Mapping, Any, Union


# ============================================================
# Environment Setup
# ============================================================

def setup_environment():
    """Install dependencies and clone repositories."""
    # Install system packages
    subprocess.run(["apt-get", "-y", "install", "-qq", "aria2", "ffmpeg"],
                   check=True, capture_output=True)

    # Install Python packages
    subprocess.run([sys.executable, "-m", "pip", "install", "-q",
                    "torch", "torchvision", "torchaudio"],
                   check=True, capture_output=True)
    subprocess.run([sys.executable, "-m", "pip", "install", "-q",
                    "torchsde", "einops", "diffusers", "accelerate"],
                   check=True, capture_output=True)
    subprocess.run([sys.executable, "-m", "pip", "install", "-q",
                    "av", "spandrel", "albumentations", "onnx",
                    "opencv-python", "onnxruntime"],
                   check=True, capture_output=True)

    # Clone ComfyUI
    os.chdir("/content")
    subprocess.run(["git", "clone", "https://github.com/comfyanonymous/ComfyUI.git"],
                   check=True, capture_output=True)
    subprocess.run([sys.executable, "-m", "pip", "install", "-q",
                    "-r", "/content/ComfyUI/requirements.txt"],
                   check=True, capture_output=True)

    # Clone custom nodes
    os.chdir("/content/ComfyUI/custom_nodes")
    custom_repos = [
        "https://github.com/city96/ComfyUI-GGUF",
        "https://github.com/whatdreamscost/whatdreamscost-comfyui",
        "https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite",
        "https://github.com/rgthree/rgthree-comfy",
        "https://github.com/kijai/ComfyUI-KJNodes",
    ]
    for repo in custom_repos:
        subprocess.run(["git", "clone", repo], check=True, capture_output=True)

    # Install custom node requirements
    for node_dir in ["ComfyUI-GGUF", "ComfyUI-KJNodes", "ComfyUI-VideoHelperSuite"]:
        req_file = f"/content/ComfyUI/custom_nodes/{node_dir}/requirements.txt"
        if os.path.exists(req_file):
            subprocess.run([sys.executable, "-m", "pip", "install", "-q",
                            "-r", req_file],
                           check=True, capture_output=True)

    os.chdir("/content/ComfyUI")
    print("Environment setup complete!")


# ============================================================
# Utility Functions
# ============================================================

os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"

import gc
import torch


def model_download(url: str, dest_dir: str, filename: str = None, silent: bool = True):
    """
    Colab-optimized download with aria2c.

    Args:
        url: Download URL
        dest_dir: Target directory (will be created if needed)
        filename: Optional output filename (defaults to URL filename)
        silent: If True, suppresses all output (except errors)

    Returns:
        The filename if successful, False if failed
    """
    try:
        Path(dest_dir).mkdir(parents=True, exist_ok=True)

        if filename is None:
            filename = url.split("/")[-1].split("?")[0]

        cmd = [
            "aria2c",
            "--console-log-level=error",
            "-c", "-x", "16", "-s", "16", "-k", "1M",
            "-d", dest_dir,
            "-o", filename,
            url
        ]

        if silent:
            cmd.extend(["--summary-interval=0", "--quiet"])
            print(f"Downloading {filename}...", end=" ", flush=True)

        result = subprocess.run(cmd, check=True, capture_output=True, text=True)

        if silent:
            print("Done!")
        else:
            print(f"Downloaded {filename} to {dest_dir}")
        return filename

    except subprocess.CalledProcessError as e:
        error = e.stderr.strip() or "Unknown error"
        print(f"\nError downloading {filename}: {error}")
        return False
    except Exception as e:
        print(f"\nError: {str(e)}")
        return False


def get_value_at_index(obj: Union[Sequence, Mapping], index: int) -> Any:
    """Returns the value at the given index of a sequence or mapping.

    If the object is a sequence (like list or string), returns the value at the given index.
    If the object is a mapping (like a dictionary), returns the value at the index-th key.

    Some return a dictionary, in these cases, we look for the "results" key

    Args:
        obj (Union[Sequence, Mapping]): The object to retrieve the value from.
        index (int): The index of the value to retrieve.

    Returns:
        Any: The value at the given index.

    Raises:
        IndexError: If the index is out of bounds for the object and the object is not a mapping.
    """
    try:
        return obj[index]
    except KeyError:
        return obj["result"][index]



import asyncio
import nest_asyncio


def import_custom_nodes() -> None:
    """Load all built-in and external custom nodes in a Jupyter/Colab-safe way."""
    from nodes import init_builtin_extra_nodes, init_external_custom_nodes

    async def loader():
        import_failed = await init_builtin_extra_nodes()
        await init_external_custom_nodes()

        if import_failed:
            print("WARNING: Some comfy_extras nodes failed to import:")
            for node in import_failed:
                print(" -", node)

    try:
        asyncio.run(loader())
    except RuntimeError:
        nest_asyncio.apply()
        loop = asyncio.get_event_loop()
        return loop.run_until_complete(loader())


# ============================================================
# Run Environment Setup
# ============================================================

setup_environment()

sys.path.insert(0, "/content/ComfyUI")

from nodes import NODE_CLASS_MAPPINGS


# ============================================================
# Model Downloads
# ============================================================

# GGUF UNet model
ltx_model_url = "https://huggingface.co/Kijai/LTXV2_comfy/resolve/main/diffusion_models/ltx-2-3-22b-dev-Q4_K_M.gguf"
dit_model = model_download(ltx_model_url, "/content/ComfyUI/models/unet")

# Text encoders
text_encoder1_url = "https://huggingface.co/Comfy-Org/ltx-2/resolve/main/split_files/text_encoders/gemma_3_12B_it_fp4_mixed.safetensors"
text_encoder1_model = model_download(text_encoder1_url, "/content/ComfyUI/models/text_encoders")

text_encoder2_url = "https://huggingface.co/Kijai/LTXV2_comfy/resolve/main/text_encoders/ltx-2.3_text_projection_bf16.safetensors"
text_encoder2_model = model_download(text_encoder2_url, "/content/ComfyUI/models/text_encoders")

# VAE models
video_vae_url = "https://huggingface.co/Kijai/LTXV2_comfy/resolve/main/VAE/LTX23_video_vae_bf16.safetensors"
video_vae_model = model_download(video_vae_url, "/content/ComfyUI/models/vae")

audio_vae_url = "https://huggingface.co/Kijai/LTXV2_comfy/resolve/main/VAE/LTX23_audio_vae_bf16.safetensors"
audio_vae_model = model_download(audio_vae_url, "/content/ComfyUI/models/vae")

tiny_vae_url = "https://huggingface.co/Kijai/LTXV2_comfy/resolve/main/VAE/taeltx2_3.safetensors"
tiny_vae_model = model_download(tiny_vae_url, "/content/ComfyUI/models/vae")

# Spatial upscaler
upscaler_url = "https://huggingface.co/Lightricks/LTX-2/resolve/main/ltx-2.3-spatial-upscaler-x2-1.1.safetensors"
upscaler_model = model_download(upscaler_url, "/content/ComfyUI/models/latent_upscale_models")

# LoRA models
lora1_url = "https://huggingface.co/Kijai/LTXV2_comfy/resolve/main/loras/ltx-2.3-22b-distilled-lora-dynamic_fro09_avg_rank_105_bf16.safetensors"
lora1_model = model_download(lora1_url, "/content/ComfyUI/models/loras")

lora2_url = "https://huggingface.co/Kijai/LTXV2_comfy/resolve/main/loras/LTX-2.3-OmniNFT-RL-Lora_bf16.safetensors"
lora2_model = model_download(lora2_url, "/content/ComfyUI/models/loras")

lora3_url = "https://huggingface.co/Kijai/LTXV2_comfy/resolve/main/loras/ltx2.3-transition.safetensors"
lora3_model = model_download(lora3_url, "/content/ComfyUI/models/loras")

lora4_url = "https://huggingface.co/Kijai/LTXV2_comfy/resolve/main/loras/LTX2.3-MVCamera-drclips.safetensors"
lora4_model = model_download(lora4_url, "/content/ComfyUI/models/loras")

print("All models downloaded successfully!")


# ============================================================
# Default Global Prompt
# ============================================================

DEFAULT_GLOBAL_PROMPT = (
    "An anthropomorphic cat family is preparing for a cinematic concert on a grand "
    "illuminated stage. The father cat, wearing a sharp black tuxedo with a gold bow tie, "
    "adjusts the microphone stand under dramatic purple and blue spotlights. The mother cat, "
    "in a flowing emerald sequined gown, tunes a vintage electric guitar while warm amber "
    "light cascades across her fur. Their kitten, dressed in a tiny leather jacket with "
    "silver studs, excitedly tests the drum kit, sticks blurring with energy. "
    "The stage features towering LED panels displaying swirling galaxies, while fog machines "
    "create low-lying atmospheric haze that catches the sweeping laser beams. "
    "Dynamic concert lighting shifts between vivid magenta, electric blue, and golden "
    "spotlights that track each family member. The camera starts with a wide establishing "
    "shot of the full stage, then smoothly dollies in for medium close-ups of each "
    "performer, capturing their intense expressions and precise movements. "
    "Strict character consistency is maintained across all frames: the father always has "
    "his distinctive white chest patch and amber eyes, the mother keeps her calico pattern "
    "and green eyes, and the kitten retains its orange tabby markings and bright blue eyes. "
    "The overall mood is epic, celebratory, and cinematic with rich contrast and "
    "professional stage lighting that creates depth and visual drama in every frame."
)


# ============================================================
# Main Pipeline Function
# ============================================================

def mainLTX(
    width: int = 1280,
    height: int = 720,
    seed: int = 0,
    frames: int = 756,
    global_prompt: str = None,
):
    """
    Execute the LTX-2.3 Director 2.0-MV pipeline programmatically.

    Args:
        width: Output video width (default 1280)
        height: Output video height (default 720)
        seed: Random seed for noise generation (default 0)
        frames: Number of frames to generate (default 756)
        global_prompt: Text prompt for generation (uses DEFAULT_GLOBAL_PROMPT if None)
    """
    if global_prompt is None:
        global_prompt = DEFAULT_GLOBAL_PROMPT

    import_custom_nodes()

    with torch.inference_mode():

        # --------------------------------------------------------
        # Step 1: Load UNet (GGUF)
        # --------------------------------------------------------
        print("Loading UNet model...")
        unetloadergguf = NODE_CLASS_MAPPINGS["UnetLoaderGGUF"]()
        unetloadergguf_135 = unetloadergguf.load_unet(
            unet_name="ltx-2-3-22b-dev-Q4_K_M.gguf"
        )

        # --------------------------------------------------------
        # Step 2: Load DualCLIP
        # --------------------------------------------------------
        print("Loading text encoders...")
        dualcliploader = NODE_CLASS_MAPPINGS["DualCLIPLoader"]()
        dualcliploader_12 = dualcliploader.load_clip(
            clip_name1=text_encoder1_model,
            clip_name2=text_encoder2_model,
            type="ltxv",
            device="default",
        )

        # --------------------------------------------------------
        # Step 3: Power Lora Loader (rgthree) - Apply 4 LoRAs
        # --------------------------------------------------------
        print("Loading LoRAs...")
        power_lora_loader = NODE_CLASS_MAPPINGS["Power Lora Loader (rgthree)"]()
        power_lora_138 = power_lora_loader.load_loras(
            model=get_value_at_index(unetloadergguf_135, 0),
            clip=get_value_at_index(dualcliploader_12, 0),
            lora_01="ltx-2.3-22b-distilled-lora-dynamic_fro09_avg_rank_105_bf16.safetensors",
            strength_01=0.4,
            lora_02="LTX-2.3-OmniNFT-RL-Lora_bf16.safetensors",
            strength_02=0.6,
            lora_03="ltx2.3-transition.safetensors",
            strength_03=0.7,
            lora_04="LTX2.3-MVCamera-drclips.safetensors",
            strength_04=0.9,
        )

        # Free text encoder memory after LoRA application
        del dualcliploader_12
        del unetloadergguf_135
        gc.collect()
        torch.cuda.empty_cache()

        # --------------------------------------------------------
        # Step 4: Load Tiny VAE (for preview override)
        # --------------------------------------------------------
        print("Loading tiny VAE for preview...")
        vaeloaderkj = NODE_CLASS_MAPPINGS["VAELoaderKJ"]()
        vaeloaderkj_6 = vaeloaderkj.load_vae(
            vae_name="taeltx2_3.safetensors",
            device="main_device",
            weight_dtype="bf16",
        )

        # --------------------------------------------------------
        # Step 5: ModelPreviewOverrideKJ
        # --------------------------------------------------------
        modelpreviewoverridekj = NODE_CLASS_MAPPINGS["ModelPreviewOverrideKJ"]()
        modelpreviewoverridekj_10 = modelpreviewoverridekj.EXECUTE_NORMALIZED(
            start_at_step=0,
            max_preview_steps=80,
            enabled=True,
            max_preview_height=240,
            fps=24,
            save_dir="",
            model=get_value_at_index(power_lora_138, 0),
            vae=get_value_at_index(vaeloaderkj_6, 0),
        )

        # Free tiny VAE
        del vaeloaderkj_6
        gc.collect()
        torch.cuda.empty_cache()

        # --------------------------------------------------------
        # Step 6: Load Audio VAE
        # --------------------------------------------------------
        print("Loading audio VAE...")
        vaeloader = NODE_CLASS_MAPPINGS["VAELoader"]()
        vaeloader_8 = vaeloader.load_vae(
            vae_name="LTX23_audio_vae_bf16.safetensors"
        )

        # --------------------------------------------------------
        # Step 7: Load Video VAE
        # --------------------------------------------------------
        print("Loading video VAE...")
        vaeloader_36 = vaeloader.load_vae(
            vae_name="LTX23_video_vae_bf16.safetensors"
        )

        # --------------------------------------------------------
        # Step 8: LTXDirector - Core pipeline node
        # --------------------------------------------------------
        print("Running LTXDirector...")
        ltxdirector = NODE_CLASS_MAPPINGS["LTXDirector"]()
        ltxdirector_131 = ltxdirector.EXECUTE_NORMALIZED(
            model=get_value_at_index(modelpreviewoverridekj_10, 0),
            clip=get_value_at_index(power_lora_138, 1),
            audio_vae=get_value_at_index(vaeloader_8, 0),
            global_prompt=global_prompt,
            width=width,
            height=height,
            frames=frames,
            fps=24,
        )

        # Free model preview
        del modelpreviewoverridekj_10
        gc.collect()
        torch.cuda.empty_cache()

        # --------------------------------------------------------
        # Step 9: ConditioningZeroOut (negative conditioning)
        # --------------------------------------------------------
        conditioningzeroout = NODE_CLASS_MAPPINGS["ConditioningZeroOut"]()
        conditioningzeroout_128 = conditioningzeroout.zero_out(
            conditioning=get_value_at_index(ltxdirector_131, 1)
        )

        # --------------------------------------------------------
        # Step 10: LTXVConditioning
        # --------------------------------------------------------
        ltxvconditioning = NODE_CLASS_MAPPINGS["LTXVConditioning"]()
        ltxvconditioning_27 = ltxvconditioning.EXECUTE_NORMALIZED(
            frame_rate=get_value_at_index(ltxdirector_131, 6),
            positive=get_value_at_index(ltxdirector_131, 1),
            negative=get_value_at_index(conditioningzeroout_128, 0),
        )

        # --------------------------------------------------------
        # Step 11: LTXDirectorGuide (Stage 1) - downscale_factor=0.5
        # --------------------------------------------------------
        print("Running LTXDirectorGuide Stage 1...")
        ltxdirectorguide = NODE_CLASS_MAPPINGS["LTXDirectorGuide"]()
        ltxdirectorguide_133 = ltxdirectorguide.EXECUTE_NORMALIZED(
            image_ref_mode="None",
            num_ref_images=1,
            downscale_factor=0.5,
            downscale_method="bicubic",
            audio_guide_scale=1,
            audio_guide_position="center",
            guide_enabled=True,
            motion_guide_enabled=False,
            max_conditioning_area=256,
            min_conditioning_area=64,
            extra_model_enabled=False,
            positive=get_value_at_index(ltxvconditioning_27, 0),
            negative=get_value_at_index(ltxvconditioning_27, 1),
            vae=get_value_at_index(vaeloader_36, 0),
            latent=get_value_at_index(ltxdirector_131, 2),
            guide_data=get_value_at_index(ltxdirector_131, 4),
            motion_guide_data=get_value_at_index(ltxdirector_131, 5),
            model=get_value_at_index(ltxdirector_131, 0),
        )

        # --------------------------------------------------------
        # Step 12: CFGGuider (Stage 1)
        # --------------------------------------------------------
        cfgguider = NODE_CLASS_MAPPINGS["CFGGuider"]()
        cfgguider_28 = cfgguider.EXECUTE_NORMALIZED(
            cfg=1,
            model=get_value_at_index(ltxdirectorguide_133, 3),
            positive=get_value_at_index(ltxdirectorguide_133, 0),
            negative=get_value_at_index(ltxdirectorguide_133, 1),
        )

        # --------------------------------------------------------
        # Step 13: Concatenate AV Latents (Stage 1)
        # --------------------------------------------------------
        ltxvconcatavlatent = NODE_CLASS_MAPPINGS["LTXVConcatAVLatent"]()
        ltxvconcatavlatent_29 = ltxvconcatavlatent.EXECUTE_NORMALIZED(
            video_latent=get_value_at_index(ltxdirectorguide_133, 2),
            audio_latent=get_value_at_index(ltxdirector_131, 3),
        )

        # --------------------------------------------------------
        # Step 14: RandomNoise (shared between both samplers)
        # --------------------------------------------------------
        randomnoise = NODE_CLASS_MAPPINGS["RandomNoise"]()
        randomnoise_30 = randomnoise.EXECUTE_NORMALIZED(
            noise_seed=seed
        )

        # --------------------------------------------------------
        # Step 15: KSamplerSelect (Stage 1) - euler
        # --------------------------------------------------------
        ksamplerselect = NODE_CLASS_MAPPINGS["KSamplerSelect"]()
        ksamplerselect_32 = ksamplerselect.EXECUTE_NORMALIZED(
            sampler_name="euler"
        )

        # --------------------------------------------------------
        # Step 16: BasicScheduler (Stage 1) - 8 steps, denoise=1.0
        # --------------------------------------------------------
        basicscheduler = NODE_CLASS_MAPPINGS["BasicScheduler"]()
        basicscheduler_33 = basicscheduler.EXECUTE_NORMALIZED(
            scheduler="linear_quadratic",
            steps=8,
            denoise=1.0,
            model=get_value_at_index(ltxdirectorguide_133, 3),
        )

        # --------------------------------------------------------
        # Step 17: SamplerCustomAdvanced (Stage 1)
        # --------------------------------------------------------
        print("Stage 1 Sampling...")
        samplercustomadvanced = NODE_CLASS_MAPPINGS["SamplerCustomAdvanced"]()
        samplercustomadvanced_31 = samplercustomadvanced.EXECUTE_NORMALIZED(
            noise=get_value_at_index(randomnoise_30, 0),
            guider=get_value_at_index(cfgguider_28, 0),
            sampler=get_value_at_index(ksamplerselect_32, 0),
            sigmas=get_value_at_index(basicscheduler_33, 0),
            latent_image=get_value_at_index(ltxvconcatavlatent_29, 0),
        )

        # Memory cleanup after Stage 1 sampling
        del cfgguider_28
        del ltxvconcatavlatent_29
        del basicscheduler_33
        gc.collect()
        torch.cuda.empty_cache()

        # --------------------------------------------------------
        # Step 18: Separate AV Latent (after Stage 1)
        # --------------------------------------------------------
        ltxvseparateavlatent = NODE_CLASS_MAPPINGS["LTXVSeparateAVLatent"]()
        ltxvseparateavlatent_34 = ltxvseparateavlatent.EXECUTE_NORMALIZED(
            av_latent=get_value_at_index(samplercustomadvanced_31, 0)
        )

        # --------------------------------------------------------
        # Step 19: LTXDirectorCropGuides (after Stage 1)
        # --------------------------------------------------------
        ltxdirectorcropguides = NODE_CLASS_MAPPINGS["LTXDirectorCropGuides"]()
        ltxdirectorcropguides_55 = ltxdirectorcropguides.EXECUTE_NORMALIZED(
            positive=get_value_at_index(ltxdirectorguide_133, 0),
            negative=get_value_at_index(ltxdirectorguide_133, 1),
            latent=get_value_at_index(ltxvseparateavlatent_34, 0),
        )

        # Free stage 1 guide and sampler output
        del ltxdirectorguide_133
        del samplercustomadvanced_31
        gc.collect()
        torch.cuda.empty_cache()

        # --------------------------------------------------------
        # Step 20: Load Latent Upscale Model
        # --------------------------------------------------------
        print("Loading spatial upscaler...")
        latentupscalemodelloader = NODE_CLASS_MAPPINGS["LatentUpscaleModelLoader"]()
        latentupscalemodelloader_13 = latentupscalemodelloader.EXECUTE_NORMALIZED(
            model_name="ltx-2.3-spatial-upscaler-x2-1.1.safetensors"
        )

        # --------------------------------------------------------
        # Step 21: LTXVLatentUpsampler
        # --------------------------------------------------------
        print("Upsampling latent...")
        ltxvlatentupsampler = NODE_CLASS_MAPPINGS["LTXVLatentUpsampler"]()
        ltxvlatentupsampler_14 = ltxvlatentupsampler.upsample_latent(
            samples=get_value_at_index(ltxdirectorcropguides_55, 2),
            upscale_model=get_value_at_index(latentupscalemodelloader_13, 0),
            vae=get_value_at_index(vaeloader_36, 0),
        )

        # Free upscale model
        del latentupscalemodelloader_13
        gc.collect()
        torch.cuda.empty_cache()

        # --------------------------------------------------------
        # Step 22: LTXDirectorGuide (Stage 2) - downscale_factor=1
        # --------------------------------------------------------
        print("Running LTXDirectorGuide Stage 2...")
        ltxdirectorguide_132 = ltxdirectorguide.EXECUTE_NORMALIZED(
            image_ref_mode="None",
            num_ref_images=1,
            downscale_factor=1,
            downscale_method="bicubic",
            audio_guide_scale=1,
            audio_guide_position="center",
            guide_enabled=True,
            motion_guide_enabled=False,
            max_conditioning_area=256,
            min_conditioning_area=64,
            extra_model_enabled=False,
            positive=get_value_at_index(ltxdirectorcropguides_55, 0),
            negative=get_value_at_index(ltxdirectorcropguides_55, 1),
            vae=get_value_at_index(vaeloader_36, 0),
            latent=get_value_at_index(ltxvlatentupsampler_14, 0),
            guide_data=get_value_at_index(ltxdirector_131, 4),
            motion_guide_data=get_value_at_index(ltxdirector_131, 5),
            model=get_value_at_index(ltxdirector_131, 0),
        )

        # Free crop guides from stage 1 and upsampled latent
        del ltxdirectorcropguides_55
        del ltxvlatentupsampler_14
        gc.collect()
        torch.cuda.empty_cache()

        # --------------------------------------------------------
        # Step 23: Concatenate AV Latents (Stage 2)
        # --------------------------------------------------------
        ltxvconcatavlatent_18 = ltxvconcatavlatent.EXECUTE_NORMALIZED(
            video_latent=get_value_at_index(ltxdirectorguide_132, 2),
            audio_latent=get_value_at_index(ltxvseparateavlatent_34, 1),
        )

        # --------------------------------------------------------
        # Step 24: KSamplerSelect (Stage 2) - euler
        # --------------------------------------------------------
        ksamplerselect_20 = ksamplerselect.EXECUTE_NORMALIZED(
            sampler_name="euler"
        )

        # --------------------------------------------------------
        # Step 25: BasicScheduler (Stage 2) - 4 steps, denoise=0.42
        # --------------------------------------------------------
        basicscheduler_21 = basicscheduler.EXECUTE_NORMALIZED(
            scheduler="linear_quadratic",
            steps=4,
            denoise=0.42,
            model=get_value_at_index(ltxdirectorguide_132, 3),
        )

        # --------------------------------------------------------
        # Step 26: CFGGuider (Stage 2)
        # --------------------------------------------------------
        cfgguider_17 = cfgguider.EXECUTE_NORMALIZED(
            cfg=1,
            model=get_value_at_index(ltxdirectorguide_132, 3),
            positive=get_value_at_index(ltxdirectorguide_132, 0),
            negative=get_value_at_index(ltxdirectorguide_132, 1),
        )

        # --------------------------------------------------------
        # Step 27: SamplerCustomAdvanced (Stage 2)
        # --------------------------------------------------------
        print("Stage 2 Sampling...")
        samplercustomadvanced_19 = samplercustomadvanced.EXECUTE_NORMALIZED(
            noise=get_value_at_index(randomnoise_30, 0),
            guider=get_value_at_index(cfgguider_17, 0),
            sampler=get_value_at_index(ksamplerselect_20, 0),
            sigmas=get_value_at_index(basicscheduler_21, 0),
            latent_image=get_value_at_index(ltxvconcatavlatent_18, 0),
        )

        # Memory cleanup after Stage 2 sampling
        del cfgguider_17
        del ltxvconcatavlatent_18
        del basicscheduler_21
        del randomnoise_30
        gc.collect()
        torch.cuda.empty_cache()

        # --------------------------------------------------------
        # Step 28: Separate AV Latent (after Stage 2)
        # --------------------------------------------------------
        ltxvseparateavlatent_22 = ltxvseparateavlatent.EXECUTE_NORMALIZED(
            av_latent=get_value_at_index(samplercustomadvanced_19, 0)
        )

        # Free stage 2 sampler output
        del samplercustomadvanced_19
        gc.collect()
        torch.cuda.empty_cache()

        # --------------------------------------------------------
        # Step 29: LTXDirectorCropGuides (after Stage 2)
        # --------------------------------------------------------
        ltxdirectorcropguides_54 = ltxdirectorcropguides.EXECUTE_NORMALIZED(
            positive=get_value_at_index(ltxdirectorguide_132, 0),
            negative=get_value_at_index(ltxdirectorguide_132, 1),
            latent=get_value_at_index(ltxvseparateavlatent_22, 0),
        )

        # Free stage 2 guide
        del ltxdirectorguide_132
        gc.collect()
        torch.cuda.empty_cache()

        # --------------------------------------------------------
        # Step 30: VAEDecode (video frames)
        # --------------------------------------------------------
        print("Decoding video...")
        vaedecode = NODE_CLASS_MAPPINGS["VAEDecode"]()
        vaedecode_1 = vaedecode.decode(
            samples=get_value_at_index(ltxdirectorcropguides_54, 2),
            vae=get_value_at_index(vaeloader_36, 0),
        )

        # Free video VAE after decoding
        del vaeloader_36
        del ltxdirectorcropguides_54
        gc.collect()
        torch.cuda.empty_cache()

        # --------------------------------------------------------
        # Step 31: LTXVAudioVAEDecode (audio)
        # --------------------------------------------------------
        print("Decoding audio...")
        ltxvaudiovaedecode = NODE_CLASS_MAPPINGS["LTXVAudioVAEDecode"]()
        ltxvaudiovaedecode_24 = ltxvaudiovaedecode.EXECUTE_NORMALIZED(
            samples=get_value_at_index(ltxvseparateavlatent_22, 1),
            audio_vae=get_value_at_index(vaeloader_8, 0),
        )

        # Free audio VAE and separation results
        del vaeloader_8
        del ltxvseparateavlatent_22
        del ltxvseparateavlatent_34
        gc.collect()
        torch.cuda.empty_cache()

        # --------------------------------------------------------
        # Step 32: VHS_VideoCombine (final output)
        # --------------------------------------------------------
        print("Combining video and audio...")
        vhs_videocombine = NODE_CLASS_MAPPINGS["VHS_VideoCombine"]()
        vhs_videocombine_139 = vhs_videocombine.combine_video(
            frame_rate=get_value_at_index(ltxdirector_131, 6),
            loop_count=0,
            filename_prefix="LTX-2.3-Director",
            format="video/h264-mp4",
            pix_fmt="yuv420p",
            crf=8,
            save_metadata=False,
            trim_to_audio=False,
            pingpong=False,
            save_output=True,
            images=get_value_at_index(vaedecode_1, 0),
            audio=get_value_at_index(ltxvaudiovaedecode_24, 0),
        )

        # Final cleanup
        del ltxdirector_131
        del vaedecode_1
        del ltxvaudiovaedecode_24
        del power_lora_138
        gc.collect()
        torch.cuda.empty_cache()

        print("Video generation complete!")
        return vhs_videocombine_139


# ============================================================
# Execute Pipeline
# ============================================================

# Video Parameters
width = 1280
height = 720
seed = 0
frames = 756

mainLTX(
    width=width,
    height=height,
    seed=seed,
    frames=frames,
    global_prompt=DEFAULT_GLOBAL_PROMPT,
)
